# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for testApp

    pod 'Firebase/Core'
    pod 'Firebase/Storage'

  target 'testApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  end

  target 'testAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


target 'testApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testApp-tvOS

end
